name: Lint Markdown
on:
  - pull_request
  - push

jobs:

  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: gem install mdl
      - run: mdl .