name: Lint Markdown
on:
  - pull_request
  - push

jobs:

  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mdl
        run: gem install mdl
      - run: mdl .